version: '3'
services:
  aria2:
    image: asdf123101/aria2-yaaw:latest
    restart: always
    ports:
      - 6800:6800
      - 6880:80
    volumes:
      - /media/store/downloads:/data
      - /aria2-config:/conf
    environment:
      - PGID=1000
      - PUID=1000
      - SECRET=sample
  plex:
    image: plexinc/pms-docker
    restart: always
    volumes:
      - plex-database:/config
      - plex-transcode:/transcode
      - plex:/data
    environment:
      - TZ="Aemrica/Toronto"
      - PLEX_CLAIM="your-token"
      - PLEX_UID=1000
      - PLEX_GID=1000
    network_mode: host
volumes:
  deluge:
  plex-database:
  plex-transcode:
  plex:
    external: true
